# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy projects and restore dependencies
COPY ["EES.API/EES.API.csproj", "EES.API/"]
COPY ["EES.Application/EES.Application.csproj", "EES.Application/"]
COPY ["EES.Domain/EES.Domain.csproj", "EES.Domain/"]
COPY ["EES.Infrastructure/EES.Infrastructure.csproj", "EES.Infrastructure/"]
RUN dotnet restore "EES.API/EES.API.csproj"

# Copy full source and build
COPY . .
WORKDIR "/src/EES.API"
RUN dotnet build "EES.API.csproj" -c Release -o /app/build

# Stage 2: Publish
FROM build AS publish
RUN dotnet publish "EES.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Stage 3: Final runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
# Corregido: --from=publish
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EES.API.dll"]